version: "3.8"

services:
  db:
    image: mariadb:10.7.3
    container_name: mariadb
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: principal
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3333:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always

volumes:
  db: